### ISSUE TITLE
Will this plugin work with magento2?

### ISSUE THREAD

**Issue by ludar** [coinbase/coinbase-magento#25]

**Comment by aianus** [comment]
I'm not sure, let me take a look tomorrow and get back to you on that.

**Comment by ludar** [comment]
Would be great if you guys had a coinbase plugin for magento2 :+1:

**Comment by fligen** [comment]
Will it work on magento 2?

**Comment by aianus** [comment]
No, but we will be releasing a new, separate plugin for Magento 2 shortly.

**Comment by aianus** [comment]
We've released a plugin for Magento 2 here: https://github.com/coinbase/coinbase-magento2

Please give it a try and let us know if you have any feedback.

**Comment by gingabox** [comment]
Hello Alex, we have gotten two notices this weekend from Coinbase saying they can't verify the callback address:


We were not able to get a valid (200) response from the callback URL you set under merchant settings.
The callback URL on your account is:
http://www.ecigexpress.com/coinbase_coinbase/callback/callback/?secret=db6c9907af93801a053a9aa8e54d0930
If 12 failures occur, this URL will be removed from your account. You can set a new callback URL at any time from the merchant settings page.



> On Mar 10, 2016, at 6:19 AM, Alex Ianus <notifications@github.com> wrote:
> 


Clicking the callback URL gives us a 401 error.  Do you happen to know what would cause this and how we can correct it?   Is this due to canceling an order?

Thanks
Ryan
